[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
via_ir = true
optimizer = true
optimizer_runs = 200
ffi = false
ast = true
build_info = true
extra_output = ["abi", "evm.bytecode"]

[rpc_endpoints]
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
arc_testnet = "${ARC_TESTNET_RPC_URL}"

[etherscan]
arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api" }
arc_testnet = { key = "${ARCSCAN_API_KEY}", url = "https://testnet.arcscan.app/api" }

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "attributes_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
